name: 02 - Push Preview and Deploy Request

on:
  pull_request:
    paths:
      - "prisma/schema.prisma"

env:
  pscale_base_directory: .pscale

jobs:
  push-to-preview:
    name: "Push to Preview"
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Connect to database
        timeout-minutes: 3
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{secrets.PLANETSCALE_SERVICE_TOKEN_ID}}
          PLANETSCALE_SERVICE_TOKEN: ${{secrets.PLANETSCALE_SERVICE_TOKEN}}
          ORG_NAME: ${{secrets.ORG_NAME}}
          DB_NAME: ${{secrets.DB_NAME}}
          GITHUB_USER: ${{github.actor}}
        working-directory: ${{env.pscale_base_directory}}/cli-helper-scripts/
        run: ./connect-database.sh

      - name: Prisma push
        run: npx prisma db push
